spring.application.name=scholar
# Server configuration
server.port=8181

# Ollama configuration
spring.ai.ollama.base-url=http://localhost:11434
# Default model, can be changed via API # llama2 # deepseek-r1:8b
# llama3.2:latest # brxce/stable-diffusion-prompt-generator:latest
# codellama:7b-instruct, phi3:mini, qwen3:4b-instruct, mistral:latest, smollm2:135m
# deepseek-r1:8b, llama3.2:latest, infosys/nt-java:latest, incept5/llama3.1-claude:latest
# deepseek-coder, starcoder2:3b
spring.ai.ollama.chat.model=smollm2:135m

#==========
# Database connection
#postgresql://postgres:postgres@host.docker.internal:5433/school
spring.datasource.url=jdbc:postgresql://localhost:5433/school
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Options for ddl-auto: none, validate, update, create, create-drop

# Show SQL in console
spring.jpa.show-sql=true

# Format SQL for readability (optional)
spring.jpa.properties.hibernate.format_sql=true

# Enable logging of SQL statements via Logback/Log4j2 (more reliable than show-sql)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# SQL initialization (optional for production) - spring.sql.init.mode=never - spring.sql.init.mode=always
#spring.sql.init.mode=never
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql

#==========

#==========
